### ISSUE TITLE
Epic 4 - Can web AR be used to create multiuser virtual meetings?

### ISSUE THREAD

**Issue by erlendb** [equinor/eit-web-ar#263]
Nowadays, many employees spend their working hours at their home office without much physical contact with others.

Can we use web AR to make a virtual meeting experience where all participants can see each other and interact with each other?

# MVP

* [x] Use a mobile phone or laptop with GPS capabilities as device
* [x] Use a web app to drive AR experience
* [x] Use altered gps positions to position the users relative to each other
* [x] Let the users "see" the other participants as if they were close by, even if they in reality are far away
* [x] Display an arrow or a map so that users can walk towards other users
* [x] Represent each user with some kind of avatar

## Stretch goals

* [ ] Make the app compatible with cardboard VR goggles
* [x] User interactions of some sort
* [x] Be able to talk with other players within a proximity, using the device's microphone
